<?php
$config=array (
  'bitfire_enabled' => true,
  'allow_ip_block' => true,
  'security_headers_enabled' => true,
  'enforce_ssl_1year' => false,
  'feature_policy_enabled' => false,
  'allowed_features' => 
  array (
    'notifications' => 'self',
    'push' => 'self',
    'geolocation' => 'self',
  ),
  'csp_policy_enabled' => false,
  'csp_default' => '*.googleapis.com *.gstatic.com \'unsafe-inline\' *.aweber.com *.wp.com ',
  'csp_policy' => 
  array (
    'font-src' => '\'self\' *.googleapis.com *.gstatic.com',
    'img-src' => '\'self\' data: *.wp.com *.aweber.com *.esurveyspro.com',
    'style-src-attr' => '\'unsafe-inline\' \'self\'',
    'style-src-elem' => '\'unsafe-inline\' \'self\' *.googleapis.com *.gstatic.com *.wigzopush.com *.paperform.co',
    'script-src' => '\'self\' *.wigzo.com *.wigzopush.com www.google-analytics.com *.woopra.com *.esurveyspro.com *.wp.com *.aweber.com',
    'object-src' => '\'none\'',
    'connect-src' => 'tracker.wigzopush.com *.google-analytics.com',
  ),
  '# mfa_phone_number' => 0,
  '# mfa_login_paths' => 
  array (
    '/foobar' => true,
  ),
  'pro_key' => '',
  'max_cache_age' => 0,
  'web_filter_enabled' => true,
  'spam_filter_enabled' => 'report',
  'xss_block' => 'block',
  'sql_block' => true,
  'file_block' => 'block',
  'block_profanity' => false,
  'filtered_logging' => 
  array (
    'cc' => true,
    'card' => true,
    'cardnumber' => true,
    'exp' => true,
    'expiration' => true,
    'cvv' => true,
    'cvv1' => true,
    'cvv2' => true,
    'pass' => true,
    'pass1' => true,
    'pass2' => true,
    'pwd' => true,
    'pwd1' => true,
    'pwd2' => true,
    'passwd' => true,
    'passwd1' => true,
    'passwd2' => true,
    'password' => true,
    'password1' => true,
    'password2' => true,
  ),
  'allowed_methods' => 
  array (
    0 => 'GET',
    1 => 'OPTIONS',
    2 => 'POST',
    3 => 'PUT',
    4 => 'HEAD',
  ),
  'whitelist_enable' => true,
  'blacklist_enable' => true,
  'require_full_browser' => false,
  'honeypot_url' => '/supreme/contact',
  'check_domain' => false,
  'valid_domains' => 
  array (
    0 => 'example-site.com',
    1 => '127.0.0.1',
    2 => 'localhost',
  ),
  'ignore_bot_urls' => 
  array (
    0 => '',
  ),
  'rate_limit' => 'report',
  'rr_5m' => 50,
  'cache_type' => 'nop',
  'cookies_enabled' => true,
  'cache_bust_parameter' => false,
  'report_file' => 'cache/alerts.json',
  'block_file' => 'cache/block.json',
  'debug_file' => '',
  'debug_header' => false,
  'browser_cookie' => '_o1PX8',
  'dashboard_path' => '/bitfire',
  'encryption_key' => 'qYUpwCvfjUKBYBQuSRt3RKjO0_VuIC0V',
  'secret' => 'uE02s8gmCiZ1LpdY3iIHJTP9G85rIaDY',
  'password' => 'bitfire!',
  'wp_root' => '',
  'debug' => false,
  'skip_local_bots' => true,
  'response_code' => 403,
  'ip_header' => 'REMOTE_ADDR',
  'dns_service' => 'localhost',
  'short_block_time' => 600,
  'medium_block_time' => 3600,
  'long_block_time' => 86400,
  'cache_ini_files' => true,
  'configured' => true,
);
